name: Testes e Cobertura

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Rodar testes com cobertura
        run: mvn clean verify

      - name: Verificar relatório JaCoCo
        run: |
          if [ ! -d "target/site/jacoco" ]; then
            echo "Relatório JaCoCo NÃO existe!"
            exit 1
          fi

          if [ -z "$(ls -A target/site/jacoco)" ]; then
            echo "Relatório JaCoCo está vazio!"
            exit 1
          fi

      - name: Upload do relatório JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
